server:
  port: 8083

spring:
  application:
    name: PostService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_CONNECTION:jdbc:mysql://localhost:3306/socialnet}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nnk070dev@gmail.com}
    password: ${MAIL_PASSWORD:mexdvjhalbdcywoj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # jwt
jwt:
  secret: 7cLINbr5ayQkxXv1sVld
  refresh:
    secret: 7fhGG38YnDFkjLkL209

firebase:
  credentials: ${FIREBASE_KEY_PATH:}