package com.example.socinetandroid.enums;

public enum SocketEvent {
    NOTIFY_ONLINE("NOTIFY ONLINE"),
    FILTER_FRIEND_STATUS("FILTER STATUS FRIEND"),
    NEW_ONLINE_USER("NEW ONLINE USER"),
    NEW_OFFLINE_USER("NEW OFFLINE USER"),
    NEW_MESSAGE("NEW MESSAGE"),
    UPDATE_MESSAGE("UPDATE MESSAGE"),
    GET_UNREAD_CONVERSATION("GET UNREAD CONVERSATION"),
    UNREAD_CONVERSATION("UNREAD CONVERSATION"),
    READ_CONVERSATION("READ CONVERSATION"),
    NEW_INVITATION("NEW INVITATION"),
    RESPONSE_INVITATION("RESPONSE INVITATION"),
    GET_ROOM_STATUS("GET ROOM STATUS"),
    NEW_ROOM("NEW ROOM"),
    NEW_ROOM_MESSAGE("NEW ROOM MESSAGE"),
    UPDATE_ROOM_MESSAGE("UPDATE ROOM MESSAGE"),
    READ_ROOM_MESSAGE("READ ROOM MESSAGE"),
    INVITE_TO_ROOM("INVITE TO ROOM"),
    NEW_MEMBER("NEW MEMBER"),
    JOIN_ROOM("JOIN ROOM"),
    JOIN_MULTI_ROOM("JOIN MULTI ROOM"),
    QUIT_ROOM("QUIT ROOM"),
    MEMBER_QUIT("MEMBER QUIT"),
    DISABLE_ROOM("DISABLE ROOM"),
    KICK_MEMBER("KICK MEMBER"),
    FORCE_LOGOUT("FORCE LOGOUT");
    private final String value;
    SocketEvent(String value) {
        this.value = value;
    }
    public String getString() {
        return value;
    }
}