server:
  port: 8888
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: '*'
            allowed-headers: '*'
            allowCredentials: true
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/account/**,/api/v1/auth/**
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**,/api/v1/friend/**
        - id: post_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/posts/**,/api/v1/comments/**,/api/v1/reactions/**
        - id: chat_service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/conversations/**,/api/v1/rooms/**
        - id: admin_service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/admin/**