server:
  port: 8084

spring:
  application:
    name: ChatService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socialnet
    username: root
    password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: nnk070dev@gmail.com
    password: mexdvjhalbdcywoj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # jwt
jwt:
  secret: 7cLINbr5ayQkxXv1sVld
  refresh:
    secret: 7fhGG38YnDFkjLkL209